### ISSUE TITLE
database/sql: memory error when scanning binary data with type sql.RawBytes for unicode characters

### ISSUE THREAD

**Issue by mcspring** [golang/go#22039]
Please answer these questions before submitting your issue. Thanks!

### What version of Go are you using (`go version`)?
go version devel +8e2d90dca8 Tue Sep 26 04:39:19 2017 +0000 darwin/amd64

### Does this issue reproduce with the latest release?
YES

### What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"

### What did you do?
I tried to read records from MySQL which stored binary data (image) to golang struct which defines data type as `sql.RawBytes`.

### What did you expect to see?
Each field setups with correct value from MySQL, including unicode characters.

### What did you see instead?
It works well for unicode characters when reading only one record. But it'll mess memory for more than one records and incorrect unicode characters already read to previous struct fields.

**Comment by ianlancetaylor** [comment]
Please provide more details, such as a program that demonstrates the problem.  Thanks.

CC @kardianos

**Comment by kardianos** [comment]
It is hard to tell from your description, but have you tried copying the data out of the RawBytes container between each row? You should be able to use the `copy` function built-in.
```
rows.Scan(&rawBytesField)
copy(rowBytes, []byte(rawBytesField))
```

**Comment by mcspring** [comment]
@ianlancetaylor 

- Here is the main codes I used. 

```go
func (m *Model) Query(query string, args ...interface{}) (result []map[string]interface{}, err error) {
	rows, err := m.db.Query(query, args...)
	if err != nil {
		return
	}

	columns, err := rows.Columns()
	if err != nil {
		return
	}
	scanValues := make([]interface{}, len(columns))

	for rows.Next() {
		for i := 0; i < len(columns); i++ {
			var value sql.RawBytes

			scanValues[i] = &value
		}

		err = rows.Scan(scanValues...)
		if err != nil {
			break
		}

		record := map[string]interface{}{}

		for i, col := range scanValues {
			record[columns[i]] = *(col.(*sql.RawBytes))
		}

		result = append(result, record)
	}

	if err = rows.Err(); err != nil {
		return
	}

	if len(result) == 0 {
		err = ErrNotFound
	}

	return
}
```

- And here is the database definitions

```
*************************** 1. row ***************************
  Field: id
   Type: int(11)
   Null: NO
    Key: PRI
Default: NULL
  Extra: auto_increment
*************************** 2. row ***************************
  Field: name
   Type: varchar(32)
   Null: NO
    Key: MUL
Default:
  Extra:
*************************** 3. row ***************************
  Field: avatar
   Type: blob
   Null: YES
    Key:
Default: NULL
  Extra:
```

@kardianos After some research, I found this issue relates to two pieces of the codes within database/sql package.

- First, we use shared container when reading data from backend which could cause mess memory?

https://github.com/golang/go/blob/master/src/database/sql/sql.go#L2491

- Second, we should copy bytes from *sql.RawBytes* when converting to dest type since *sql.RawBytes* is a *[]byte*

https://github.com/golang/go/blob/master/src/database/sql/convert.go#L258
