### ISSUE TITLE
x/build/cmd/coordinator/buildongce: test failure

### ISSUE THREAD

**Issue by eclipseo** [golang/go#26476]
### What version of Go are you using (`go version`)?
Go 1.11 beta 1

### Does this issue reproduce with the latest release?
Yeah

### What operating system and processor architecture are you using (`go env`)?
Fedora 29 x86_64, ppc64le, aarch64, i686, s390x, armv7hl

```
Testing: "/builddir/build/BUILD/build-9e3b83b06d155ee6fce008d9b842cf5e49797ae2/_build/src/golang.org/x/build/cmd/coordinator/buildongce"
+ GOPATH=/builddir/build/BUILD/build-9e3b83b06d155ee6fce008d9b842cf5e49797ae2/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld '\'''
--- FAIL: TestDeploymentManagerManifest (0.00s)
    create_test.go:53: Rendered template did not match. Rendered: 
        resources:
        - name: "buildlets"
          type: container.v1.cluster
          properties:
            zone: "us-central1-f"
            cluster:
              initial_node_count: 1
              network: "default"
              logging_service: "logging.googleapis.com"
              monitoring_service: "none"
              node_config:
                machine_type: "n1-standard-4"
                oauth_scopes:
                  - "https://www.googleapis.com/auth/cloud-platform"
                  - "https://www.googleapis.com/auth/userinfo.email"
              master_auth:
                username: "admin"
                password: ""
        
        
        Expected: 
        resources:
        - name: "buildlets"
          type: container.v1.cluster
          properties:
            zone: "us-central1-f"
            cluster:
              initial_node_count: 1
              network: "default"
              logging_service: "logging.googleapis.com"
              monitoring_service: "none"
              node_config:
                machine_type: "n1-standard-8"
                oauth_scopes:
                  - "https://www.googleapis.com/auth/cloud-platform"
                  - "https://www.googleapis.com/auth/userinfo.email"
              master_auth:
                username: "admin"
                password: ""
FAIL
exit status 1
FAIL	golang.org/x/build/cmd/coordinator/buildongce	0.013s
```
