### ISSUE TITLE
net: udp packets not load balanced by kubernetes service

### ISSUE THREAD

**Issue by MaurGi** [golang/go#31427]
### What version of Go are you using (`go version`)?

<pre>
$ go version go1.10.4 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
`sudo apt-get update && sudo apt-get install golang` tells me I am on the latest version.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/maurgi/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/maurgi/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build890901110=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What did you do?

I have a simple udp server that just receives packets deployed as a Kubernetes Service with 3 instances.
Then with a simple udp client I call `conn = net.Dial` and in a forever  loop I call `conn.Write`

### What did you expect to see?

UDP packets are randomly distributed across the three pods.

### What did you see instead?

UDP packets ALWAYS go to the same server until I stop the client.
If I try to use netcat, the packets correctly go to the right server.

Server:
```go
package main

import (
	"fmt"
	"net"
)

func main() {
	tcpListener, err := net.Listen("tcp", "0.0.0.0:3333")
	checkError(err)
	defer tcpListener.Close()
	fmt.Println("TCP-Listening on 0.0.0.0:3333")

	udpListener, err := net.ListenPacket("udp", "0.0.0.0:3333")
	checkError(err)
	defer udpListener.Close()
	fmt.Println("UDP-Listening on 0.0.0.0:3333")

	go listenUDP(udpListener)

	for {
		tcpConn, err := tcpListener.Accept()
		checkError(err)
		defer tcpConn.Close()
		fmt.Println("TCP-Connected")

		go handleTCPConn(tcpConn)
	}
}

func handleTCPConn(conn net.Conn) {
	// Make a buffer to hold incoming data.
	buf := make([]byte, 1024)
	i := 0

	for {
		// Read the incoming connection into the buffer.
		_, err := conn.Read(buf)
		if err != nil {
			fmt.Println("TCP connection error ", err.Error())
			break
		}

		// Log what received
		fmt.Printf("%d - TCP:%s", i, buf)
		i++
	}
}

func listenUDP(udpListener net.PacketConn) {
	buffer := make([]byte, 1024)
	i := 0

	for {
		//simple read
		udpListener.ReadFrom(buffer)

		// Log what received
		fmt.Printf("%d - UDP:%s", i, buffer)
		i++
	}
}

func checkError(err error) {
	if err != nil {
		fmt.Println("Fatal error ", err.Error())
		panic(err)
	}
}
```

Client:
```go
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"log"
	"net"
	"syscall"
	"time"
)

func handleError(err error) {
	if err != nil {
		log.Fatalf("Error with the statsd connection %s", err.Error())
		panic(err)
	}
}

// From https://github.com/go-sql-driver/mysql/blob/master/conncheck.go
// Note that it works only on Unix, and it caused several allocations.
// I really want this is implemented in stdlib in efficient (and probably cross platform) way.
var errUnexpectedRead = errors.New("unexpected read from socket")

func connCheck(c net.Conn) error {
	var (
		n    int
		err  error
		buff [1]byte
	)

	sconn, ok := c.(syscall.Conn)
	if !ok {
		return nil
	}
	rc, err := sconn.SyscallConn()
	if err != nil {
		return err
	}
	rerr := rc.Read(func(fd uintptr) bool {
		n, err = syscall.Read(int(fd), buff[:])
		return true
	})
	switch {
	case rerr != nil:
		return rerr
	case n == 0 && err == nil:
		return io.EOF
	case n > 0:
		return errUnexpectedRead
	case err == syscall.EAGAIN || err == syscall.EWOULDBLOCK:
		return nil
	default:
		return err
	}
}

func runClient(server *string, port *string, protocol *string, sleep int) {
	address := fmt.Sprintf("%s:%s", *server, *port)
	prot := *protocol
	conn, err := net.Dial(prot, address)
	handleError(err)

	for {
		msg := fmt.Sprintf("%sTEST\n", prot)
		log.Printf("Sending message: %s", msg)
		_, err := conn.Write([]byte(msg))
		handleError(err)

		if prot == "tcp" {
			err := connCheck(conn)
			handleError(err)
		}

		time.Sleep(time.Duration(sleep) * time.Second)
	}
}

func main() {
	// Command flag: https://gobyexample.com/command-line-flags
	var srv, port, protocol string
	var sleep int
	flag.StringVar(&srv, "server", "127.0.0.1", "the target server")
	flag.StringVar(&port, "port", "3333", "the target port")
	flag.StringVar(&protocol, "protocol", "tcp", "protocol used [tcp|udp]")
	flag.IntVar(&sleep, "sleep", 1, "sleep seconds")

	flag.Parse()

	fmt.Printf("using server: %s, port: %s, protocol: %s, sleep seconds:%d\n", srv, port, protocol, sleep)
	runClient(&srv, &port, &protocol, sleep)
}
```

Kubernetes deployment:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: multiport
  name: multiport
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      run: multiport
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: multiport
    spec:
      containers:
      - image: multiport:latest
        imagePullPolicy: IfNotPresent
        name: multiport
        ports:
        - containerPort: 3333
          protocol: TCP
        - containerPort: 3333
          protocol: UDP
        resources: {}
```

Kubernetes service:
```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    run: multiport
  name: multiport
  namespace: default
spec:
  ports:
  - port: 3333
    protocol: UDP
  #  targetPort: 3333
  #  name: udp-port
  selector:
    run: multiport
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

launch the client with:
```
go run test_client.go -server multiport.default -port 3333 -protocol udp
```

verify that the packets go to the same server until you stop and restart the client

run a test from bash with:
```
for i in {1..100}; do echo "sending"; echo "TEST" | nc -w 1 -u multiport.default 3333; done
```

verify that the packets end on different servers
