### ISSUE TITLE
x/pkgsite: <input class="DetailsHeader-pathInput"> element is floating strangely

### ISSUE THREAD

**Issue by dmitshur** [golang/go#38162]
### What is the URL of the page with the issue?

https://pkg.go.dev/cmd/link?tab=doc

### What is your user agent?

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36` 
 
### Screenshot

![image](https://user-images.githubusercontent.com/1924134/77943572-6c3a4480-728b-11ea-926d-07f200c35e34.png)
 
### What did you do?
 
I visited the page. 
 
### What did you expect to see?
 
A consistent page background.

### What did you see instead?

An \<input\> element floating strangely on the left hand side.

Its CSS properties are:

```
left: -62rem;
position: absolute;
top: 62rem;
```

This might be related to #36809.

/cc @jba @julieqiu

**Comment by jba** [comment]
An input element is needed to support copying to the clipboard. (Unless it isn't. That would be nice. But as far as I know it is.)

I had to put that element somewhere. I guess I didn't put it far enough away.

**Comment by dmitshur** [comment]
Do you know if making its opacity 0 a viable alternative?

**Comment by nyaascii** [comment]
> An input element is needed to support copying to the clipboard. (Unless it isn't. That would be nice. But as far as I know it is.)
> 
> I had to put that element somewhere. I guess I didn't put it far enough away.

Hello!

There is [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API) but it requires permission from [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API). Unfortunately, Internet Explorer doesn't support this at all.

Clipboard API compatibility chart:
![Chart 1](https://user-images.githubusercontent.com/17256443/84901413-bae9c480-b0ab-11ea-9143-60175af0a47b.png)

Permissions API compatibility chart:
![Chart 2](https://user-images.githubusercontent.com/17256443/84901478-d0f78500-b0ab-11ea-94da-f16da2789099.png)

Thank you 🙇‍♀️

**Comment by nyaascii** [comment]
Tested the change on 3840 x 2160 px display:
![4k](https://user-images.githubusercontent.com/17256443/84915884-a8788680-b0bd-11ea-9460-2c494655ab53.png)

And on 1920 x 1080 px display:
![fhd](https://user-images.githubusercontent.com/17256443/84916200-0c02b400-b0be-11ea-8c1e-a25185e6d553.png)

I just changed `-62rem` to `-50vw`, so it should always "hide" correctly:
```css
.DetailsHeader-pathInput {
  /*
   * An input element that can be selected so its contents can be
   * copied to the clipboard. We can't use a hidden element, so
   * put this visible one very far off the screen.
   */
  left: -50vw;
  position: absolute;
  top: 62rem;
}
```

Maybe `top` should be changed as well (to e.g. `50vh`)?

Thank you for your time 🙇‍♀️
