### ISSUE TITLE
go.dev: Help removing packages under go.opentelemetry.io

### ISSUE THREAD

**Issue by bogdandrutu** [golang/go#39103]
### What is the URL of the page with the issue?
 https://pkg.go.dev/mod/go.opentelemetry.io?tab=packages
 
### What did you do?
 
Initially using https://github.com/GoogleCloudPlatform/govanityurls.git we publish modules directly under `go.opentelemetry.io` but later because we found that we will have more repos we decided to use different paths to export different repositories

```yaml
/otel:
  repo: https://github.com/open-telemetry/opentelemetry-go
/collector:
  repo: https://github.com/open-telemetry/opentelemetry-collector
/contrib/otel:
  repo: https://github.com/open-telemetry/opentelemetry-go-contrib
/contrib/collector:
  repo: https://github.com/open-telemetry/opentelemetry-collector-contrib
```
 
Before we had (which we replaced 6 moths ago, and never used):
```yaml
/:
  repo: https://github.com/open-telemetry/opentelemetry-go
```

### What did you expect to see?

I would expect all the old packages that we exported previously https://pkg.go.dev/mod/go.opentelemetry.io?tab=packages to be gone.
 
 
### What did you see instead?

I would expect to have only packages under https://pkg.go.dev/mod/go.opentelemetry.io/otel?tab=packages
