### ISSUE TITLE
syscall: TestRlimit fails on darwin amd64 @ go1.17beta1

### ISSUE THREAD

**Issue by tamird** [golang/go#46705]
### What version of Go are you using (`go version`)?

Merge of go1.17beta1 into Fuchsia's fork.
<pre>
$ go version
go1.17beta1
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

Seen in CI, but looks like macOS 10.15.7

https://ci.chromium.org/p/fuchsia/builders/try/go-x64-mac/b8844749611402529808

Full environment below:

### What did you do?

https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket.appspot.com/8844749611402529808/+/u/test/execution_details

```
Executing command [
  '/opt/s/w/ir/x/w/go/src/run.bash',
  '--no-rebuild',
]
escaped for shell: /opt/s/w/ir/x/w/go/src/run.bash --no-rebuild
in dir /opt/s/w/ir/x/w/go/src
at time 2021-06-10T21:45:10.318236
LUCI_CONTEXT:
  'realm': {}
  'luciexe': {'cache_dir': u'/opt/s/w/ir/cache'}
  'deadline': {'grace_period': 30.0, 'soft_deadline': 1623394922.042602}
full environment:
  BOTO_CONFIG: /opt/s/w/ir/x/a/gsutil-bbagent/.boto
  BUILDBUCKET_EXPERIMENTAL: FALSE
  CIPD_CACHE_DIR: /opt/s/cipd_cache/cache
  CIPD_PROTOCOL: v2
  CLOUDSDK_CONFIG: /opt/s/w/ir/x/a/gcloud-bbagent
  DOCKER_CONFIG: /opt/s/w/ir/x/a/docker-cfg-bbagent
  DOCKER_TMPDIR: /opt/s/w/ir/x/a/docker-tmp-bbagent
  FIREBASE_TOKEN: ignored-non-empty-value
  FIREBASE_TOKEN_URL: http://127.0.0.1:49402
  GCE_METADATA_HOST: 127.0.0.1:49401
  GCE_METADATA_IP: 127.0.0.1:49401
  GCE_METADATA_ROOT: 127.0.0.1:49401
  GIT_CONFIG_NOSYSTEM: 1
  GIT_TERMINAL_PROMPT: 0
  GOARCH: amd64
  GOOS: darwin
  GOROOT_BOOTSTRAP: /opt/s/w/ir/x/w/cipd/go
  HOME: /Users/chrome-bot
  INFRA_GIT_WRAPPER_HOME: /opt/s/w/ir/x/a/git-home-bbagent
  ISOLATED_RESOLVED_PACKAGE_VERSIONS_FILE: /opt/s/w/itPN_4Xr/cipd_info.json
  LOGDOG_COORDINATOR_HOST: logs.chromium.org
  LOGDOG_NAMESPACE: u/test/u
  LOGDOG_STREAM_PREFIX: buildbucket/cr-buildbucket.appspot.com/8844749611402529808
  LOGDOG_STREAM_PROJECT: fuchsia
  LOGDOG_STREAM_SERVER_PATH: unix:/opt/s/w/ir/x/ld/sock.253173043
  LOGNAME: chrome-bot
  LUCI_CONTEXT: /opt/s/w/itPN_4Xr/luci_context.026137053
  MAC_CHROMIUM_TMPDIR: /opt/s/w/ir/x/t
  NO_GCE_CHECK: False
  PATH: /opt/s/w/ir/x/w/go/bin:/opt/s/w/ir/cipd_bin_packages:/opt/s/w/ir/cipd_bin_packages/bin:/opt/s/w/ir/cipd_bin_packages/cpython:/opt/s/w/ir/cipd_bin_packages/cpython/bin:/opt/s/w/ir/cipd_bin_packages/cpython3:/opt/s/w/ir/cipd_bin_packages/cpython3/bin:/opt/s/cipd_cache/bin:/opt/local/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/git/bin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  PYTHONIOENCODING: UTF-8
  PYTHONUNBUFFERED: 1
  SHELL: /bin/zsh
  SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.sBPFOZe07f/Listeners
  SWARMING_BOT_ID: build954-m9
  SWARMING_EXTERNAL_BOT_SETUP: 1
  SWARMING_HEADLESS: 1
  SWARMING_SERVER: https://chromium-swarm.appspot.com
  SWARMING_TASK_ID: 541231ff5fa08411
  TEMP: /opt/s/w/ir/x/t
  TEMPDIR: /opt/s/w/ir/x/t
  TMP: /opt/s/w/ir/x/t
  TMPDIR: /opt/s/w/ir/x/t
  USER: chrome-bot
  VERSIONER_PYTHON_VERSION: 2.7
  VPYTHON_VIRTUALENV_ROOT: /opt/s/w/ir/cache/vpython
  XPC_FLAGS: 0x0
  XPC_SERVICE_NAME: org.swarm.bot.plist
  __CF_USER_TEXT_ENCODING: 0x1F4:0x0:0x0

Step had exit code: 1 (a.k.a. 0x00000001)
```

### What did you expect to see?

All tests passed.

### What did you see instead?

```

##### Testing packages.
...
--- FAIL: TestRlimit (0.00s)
    syscall_unix_test.go:354: Setrlimit: restore failed: syscall.Rlimit{Cur:0xffff, Max:0x7fffffffffffffff} invalid argument
FAIL
FAIL	syscall	0.849s
...
FAIL
go tool dist: Failed: exit status 1
```

*This test didn't change between go1.16.3 and go1.17beta1, but the implementation did. The test passes on go1.16.3.*

@tklauser
