### ISSUE TITLE
x/vulndb: improve tool for creating yaml reports

### ISSUE THREAD

**Issue by julieqiu** [golang/go#50314]
cmd/vulnreport should be updated with the following functionality:

Given a GitHub issue ID:

- [x] Parse the CVE ID from the GitHub issue
- [x] Parse the JSON file from the CVE list repo
- [x] Create a yaml file with the correct filename, and populate it as much as possible

Template:
```
module:
package:
versions:
  - introduced:
  - fixed:
description: |

cve:
credit:
symbols:
  -
published:
links:
  commit:
  pr:
  context:
    -
```
