### ISSUE TITLE
runtime: fail with: `Fatal glibc error: rseq registration failed`

### ISSUE THREAD

**Issue by belimawr** [golang/go#51315]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17.7 linux/amd64
</pre>

### Does this issue reproduce with the latest release?
Yes

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/tiago/.cache/go-build"
GOENV="/home/tiago/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/tiago/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/tiago/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17.7"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/tiago/go/src/github.com/elastic/beats/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3405069067=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What did you do?
I built [filebeat](https://github.com/elastic/beats) and run it, then I get this message:
```
Fatal glibc error: rseq registration failed
zsh: IOT instruction (core dumped)  ./filebeat -c ./config.yml > /dev/null
```

I looked at the core dump with delve and that's what I got:
```
0  0x0000000000f5d8a1 in runtime.raise
   at /usr/local/go/src/runtime/sys_linux_amd64.s:165
1  0x0000000000f5bfe1 in runtime.goexit
   at /usr/local/go/src/runtime/asm_amd64.s:1581
```

The issue started when I updated my system (Arch Linux) and as part of the update glibc was updated to 2.35.

Somehow it seems related to starting threads, so I have not managed to reproduce on a simple Go program.

I'm not sure if this is an issue with glibc or the way the Go runtime interacts with it. The rest of my system is stable, so I'm inclined to believe it's Go related. I have not changed my application at all, just the system update. I also had the same behaviour with an older Go version (1.16 I believe). I also have some colleges reporting similar problems when running Go programs.

Disabling CGO when compiling makes the issue go away.

I see the same issues on an Arch Linux VM running glibc 2.35 and the latest Go compiler
Everything works on a Arch Linux with glibc 2.33.

Some more information about my environment:
Linux distro: Arch Linux
```
$ pacman -Ss glibc | grep installed
core/glibc 2.35-2 [installed]
extra/nss-mdns 0.15.1-1 [installed]

$ uname -a
Linux x-wing 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

$ go version
go version go1.17.7 linux/amd64
```

#### Full steps to reproduce
Clone, compile and run filebeat:
```sh
git clone https://github.com/elastic/beats
cd beats/filebeat
go build .
./filebeat -c ./config.yml
```

The `config.yml` file is this:
```yaml
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /home/tiago/sandbox/filestream-duplication/first.log
  fields:
    app.name: "first"
  fields_under_root: true
  parsers:
    - ndjson:
        keys_under_root: true
        add_error_key: true

- type: filestream
  enabled: true
  paths:
    - /home/tiago/sandbox/filestream-duplication/to-append.log
  fields:
    app.name: "second"
  fields_under_root: true
  fields_under_root: true
  parsers:
    - ndjson:
        keys_under_root: true
        add_error_key: true

output.console:
  enabled: true

#logging.level: debug
logging.to_stderr: true
#logging.selectors: ["havester", "filestream"]
logging.selectors: ["input.filestream", "file_watcher", "input_type"]
logging.metrics.enabled: false
logging.to_files: false

path.home: ./_tmp
```

### What did you expect to see?
The program to run normally.

### What did you see instead?
The program crashing and a core dump generated. Most of the times it breaks, but some times (very few times) it just runs without any issue.
