### ISSUE TITLE
x/talks/present: display slide numbers

### ISSUE THREAD

**Issue by Sajmani** [golang/go#5331]
<pre>Audience members may have questions about specific slides.  Present should display a
slide number so that people can ask about &quot;slide 23&quot; instead of &quot;the
slide before the one with the cartwheeling gopher on it&quot;.</pre>

**Comment by nmcclain** [comment]
The page number is already available to the template, so you just have to call it from this template file: ```cmd/present/templates/slides.tmpl```

Add ```<div class="pagenumber">{{$s.Number}}</div>``` just before ```</article>```

Here's some sample CSS to add to ```cmd/present/static/styles.css```:
```css
div.pagenumber {
  color: #666;
  position: absolute;
  bottom:0;
  right:0;
  padding-right:10px;
  font-size: 80%;
}
```
