### ISSUE TITLE
govulncheck-action: Warning: Both go-version and go-version-file inputs are specified, only go-version will be used while only 'go-version-file: go.mod' is specified

### ISSUE THREAD

**Issue by sbp-bvanb** [golang/go#70036]
### govulncheck version

golang/govulncheck-action@v1.0.4

### Does this issue reproduce at the latest version of golang.org/x/vuln?

-

### Output of `go env` in your module/workspace:

```shell
-
```

### What did you do?

```
- uses: golang/govulncheck-action@v1.0.4
  with:
    go-version-file: go.mod
    go-package: ./...
```

### What did you see happen?

Warning: Both go-version and go-version-file inputs are specified, only go-version will be used

### What did you expect to see?

No warning as `go-version-file: go.mod` has been defined. If this is the case, then the code should omit go-version and only use the version that is defined in the go.mod file. Now it is using another Golang version, while another version is defined in the go.mod file.

**Comment by cagedmantis** [comment]
cc [@golang/vulndb](https://github.com/orgs/golang/teams/vulndb)

**Comment by waliseddiqi** [comment]
I am having same issue 

reproduction:
I wanted to pass `go-version-file` which is `1.23.2` in my go.mod project but the action assigned the go version as `1.23.3`

Warning: Both go-version and go-version-file inputs are specified, only go-version will be used

**Comment by jasonwashburn** [comment]
Looks like the issue was likely introduced [here](https://github.com/golang/govulncheck-action/commit/b625fbe08f3bccbe446d94fbf87fcc875a4f50ee). By giving `go-version-input` a default value, it guarantees that the setup-go action will be provided a 'go-version' input even when the user does not specify one and the a user-specified `go-version-file` will be ignored by setup-go

**Comment by jqdurham** [comment]
Just adding a +1 to this issue.  We build off the Go version our go.mod which is problematic if govulncheck is not aligned.

**Comment by julio-lopez** [comment]
Workaround: specify an empty `go-version-input`.

```
- uses: golang/govulncheck-action@v1.0.4
  with:
    go-version-file: go.mod
    go-version-input:
    go-package: ./...
```
