### ISSUE TITLE
govulncheck-action: Support using a later patch release than what's in go.mod

### ISSUE THREAD

**Issue by kaovilai** [golang/go#70853]
### Go version

n/a

### Output of `go env` in your module/workspace:

```shell
n/a
```

### What did you do?

want to use later golang than go.mod but compatible with go.mod

Support using a later patch release than what's in go.mod

Please ensure the action inherits https://github.com/actions/setup-go/issues/481 when implemented.

### What did you see happen?

1.22.0 go.mod results in 1.22.0 being used and no option to use later 1.22

### What did you expect to see?

1.22.0 go.mod should use 1.22.7+ or latest available compatible with 1.22.0

**Comment by hyangah** [comment]
Sorry that I may be misunderstanding. Isn't `check-latest` going to do the right thing already? Or can't you use `go-version-input` with `check-latest` instead of `go-version-file`? 

Out of curiosity: 

1) what prevents from running `go run golang.org/x/vuln/cmd/govulncheck@latest` directly from your own github action workflow set up with actions/setup-go? That will give you a full control over how you want to configure Go in your CI. Looks like almost half of the configuration knobs in the current [arrangement](https://github.com/golang/govulncheck-action/blob/master/action.yml) are to use `actions/setup-go` rather than the govulncheck invocation itself.

2) why do you want to use a newer version than the min version specified in the go.mod when scanning for vulnerability? if a module requires 1.22 (or 1.22.0) in its go.mod, but is affected by a vulnerability fixed in 1.22.7, the mentioned setup may prevent detection of the vulnerability. If that module is a library module, ideally the module should change their go.mod to specify 1.22.7 as the minimum requirement. Isn't it?

**Comment by kaovilai** [comment]
> Isn't check-latest going to do the right thing already?

@hyangah  no, see.
https://github.com/kopia/kopia/actions/runs/12328329173/job/34421677211?pr=4303#step:4:26

Recent run
```
Run actions/setup-go@v5.0.0
  with:
    check-latest: true
    go-version-file: go.mod
    cache: false
    token: ***
  env:
    UNIX_SHELL_ON_WINDOWS: true
    ENABLE_UNICODE_FILENAMES: 
    ENABLE_LONG_FILENAMES: 
Setup go version spec 1.22.0
```

This issue is to ensure that however govulncheck-action is adopting setup-go, that it is working in govulncheck-action.
